using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DtekMonitor.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create telegram schema if not exists
            migrationBuilder.Sql("CREATE SCHEMA IF NOT EXISTS telegram;");

            // =============================================
            // Subscribers table - may already exist from EnsureCreated
            // =============================================
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Subscribers"" (
                    ""ChatId"" bigint NOT NULL,
                    ""GroupName"" character varying(10) NOT NULL,
                    ""Username"" character varying(100),
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Subscribers"" PRIMARY KEY (""ChatId"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Subscribers_GroupName"" ON ""Subscribers"" (""GroupName"");
            ");

            // =============================================
            // telegram.Users table - SDK entity
            // =============================================
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS telegram.""Users"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""TelegramId"" bigint NOT NULL,
                    ""Username"" character varying(64),
                    ""FirstName"" character varying(128),
                    ""LastName"" character varying(128),
                    ""LanguageCode"" character varying(10),
                    ""IsPremium"" boolean NOT NULL,
                    ""IsBlocked"" boolean NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""BlockedAt"" timestamp with time zone,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    ""LastActivityAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_TelegramId"" ON telegram.""Users"" (""TelegramId"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Users_IsActive"" ON telegram.""Users"" (""IsActive"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Users_LastActivityAt"" ON telegram.""Users"" (""LastActivityAt"");
            ");

            // =============================================
            // telegram.MessageLogs table - SDK entity
            // =============================================
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS telegram.""MessageLogs"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""TelegramUserId"" bigint,
                    ""TelegramMessageId"" integer NOT NULL,
                    ""ChatId"" bigint NOT NULL,
                    ""MessageText"" character varying(4096),
                    ""MessageType"" character varying(32) NOT NULL,
                    ""IsCommand"" boolean NOT NULL,
                    ""CommandName"" character varying(64),
                    ""ReceivedAt"" timestamp with time zone NOT NULL,
                    ""ProcessedSuccessfully"" boolean NOT NULL,
                    ""ErrorMessage"" character varying(1024),
                    CONSTRAINT ""PK_MessageLogs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_MessageLogs_Users_TelegramUserId"" 
                        FOREIGN KEY (""TelegramUserId"") REFERENCES telegram.""Users"" (""Id"") ON DELETE SET NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_MessageLogs_ChatId"" ON telegram.""MessageLogs"" (""ChatId"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_MessageLogs_ReceivedAt"" ON telegram.""MessageLogs"" (""ReceivedAt"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_MessageLogs_ChatId_ReceivedAt"" ON telegram.""MessageLogs"" (""ChatId"", ""ReceivedAt"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_MessageLogs_TelegramUserId"" ON telegram.""MessageLogs"" (""TelegramUserId"");
            ");

            // =============================================
            // telegram.CallbackLogs table - SDK entity
            // =============================================
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS telegram.""CallbackLogs"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""TelegramUserId"" bigint,
                    ""CallbackQueryId"" character varying(128) NOT NULL,
                    ""ChatId"" bigint,
                    ""CallbackData"" character varying(256),
                    ""ReceivedAt"" timestamp with time zone NOT NULL,
                    ""ProcessedSuccessfully"" boolean NOT NULL,
                    ""ErrorMessage"" character varying(1024),
                    CONSTRAINT ""PK_CallbackLogs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_CallbackLogs_Users_TelegramUserId"" 
                        FOREIGN KEY (""TelegramUserId"") REFERENCES telegram.""Users"" (""Id"") ON DELETE SET NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_CallbackLogs_ChatId"" ON telegram.""CallbackLogs"" (""ChatId"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_CallbackLogs_ReceivedAt"" ON telegram.""CallbackLogs"" (""ReceivedAt"");
            ");
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_CallbackLogs_TelegramUserId"" ON telegram.""CallbackLogs"" (""TelegramUserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CallbackLogs",
                schema: "telegram");

            migrationBuilder.DropTable(
                name: "MessageLogs",
                schema: "telegram");

            migrationBuilder.DropTable(
                name: "Subscribers");

            migrationBuilder.DropTable(
                name: "Users",
                schema: "telegram");
        }
    }
}
